use commonware_codec::{EncodeSize, Error, FixedSize, Read, ReadExt, Write};
use commonware_cryptography::sha256::Digest;
use nunchi_common::Address;

/// Maximum markets tracked by one CLOB ledger instance.
pub const MAX_MARKETS: usize = 4096;
/// Maximum open order ids retained on one side of one market.
pub const MAX_BOOK_ORDERS: usize = 8192;
/// Maximum order ids retained for one account query index.
pub const MAX_ACCOUNT_ORDERS: usize = 8192;
/// Maximum fill ids retained for one market query index.
pub const MAX_FILLS_PER_MARKET: usize = 16_384;
/// Maximum signed order intents carried by one proposed match batch.
pub const MAX_MATCH_BATCH_ORDERS: usize = 4_096;
/// Maximum fills carried by one proposed match batch.
pub const MAX_MATCH_BATCH_FILLS: usize = 4_096;

/// Deterministic identifier for a traded asset.
///
/// The CLOB keeps this generic so spot, perps, house, and batch-clearing clients
/// can agree on asset ids without coupling order matching to a settlement module.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AssetId(pub Digest);

/// Stable identifier for a base/quote market.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MarketId(pub Digest);

/// Stable identifier for an order accepted by the book.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct OrderId(pub Digest);

/// Stable identifier for a match generated by the book.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct FillId(pub Digest);

macro_rules! digest_id_codec {
    ($ty:ty) => {
        impl Write for $ty {
            fn write(&self, buf: &mut impl bytes::BufMut) {
                self.0.write(buf);
            }
        }

        impl Read for $ty {
            type Cfg = ();

            fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
                Ok(Self(Digest::read(buf)?))
            }
        }

        impl FixedSize for $ty {
            const SIZE: usize = Digest::SIZE;
        }
    };
}

digest_id_codec!(AssetId);
digest_id_codec!(MarketId);
digest_id_codec!(OrderId);
digest_id_codec!(FillId);

/// Side of the book an order rests on.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Side {
    Bid,
    Ask,
}

impl Side {
    pub fn opposite(self) -> Self {
        match self {
            Self::Bid => Self::Ask,
            Self::Ask => Self::Bid,
        }
    }

    pub fn crosses(self, taker_price: u128, maker_price: u128) -> bool {
        match self {
            Self::Bid => taker_price >= maker_price,
            Self::Ask => taker_price <= maker_price,
        }
    }
}

impl Write for Side {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        match self {
            Self::Bid => 0_u8.write(buf),
            Self::Ask => 1_u8.write(buf),
        }
    }
}

impl Read for Side {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        match u8::read(buf)? {
            0 => Ok(Self::Bid),
            1 => Ok(Self::Ask),
            tag => Err(Error::InvalidEnum(tag)),
        }
    }
}

impl EncodeSize for Side {
    fn encode_size(&self) -> usize {
        1
    }
}

/// Resting behavior for unfilled quantity.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TimeInForce {
    GoodTilCancelled,
    ImmediateOrCancel,
}

impl Write for TimeInForce {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        match self {
            Self::GoodTilCancelled => 0_u8.write(buf),
            Self::ImmediateOrCancel => 1_u8.write(buf),
        }
    }
}

impl Read for TimeInForce {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        match u8::read(buf)? {
            0 => Ok(Self::GoodTilCancelled),
            1 => Ok(Self::ImmediateOrCancel),
            tag => Err(Error::InvalidEnum(tag)),
        }
    }
}

impl EncodeSize for TimeInForce {
    fn encode_size(&self) -> usize {
        1
    }
}

/// Lifecycle state of an order.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OrderStatus {
    Open,
    PartiallyFilled,
    Filled,
    Cancelled,
    Expired,
}

impl OrderStatus {
    pub fn is_open(self) -> bool {
        matches!(self, Self::Open | Self::PartiallyFilled)
    }
}

impl Write for OrderStatus {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        match self {
            Self::Open => 0_u8.write(buf),
            Self::PartiallyFilled => 1_u8.write(buf),
            Self::Filled => 2_u8.write(buf),
            Self::Cancelled => 3_u8.write(buf),
            Self::Expired => 4_u8.write(buf),
        }
    }
}

impl Read for OrderStatus {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        match u8::read(buf)? {
            0 => Ok(Self::Open),
            1 => Ok(Self::PartiallyFilled),
            2 => Ok(Self::Filled),
            3 => Ok(Self::Cancelled),
            4 => Ok(Self::Expired),
            tag => Err(Error::InvalidEnum(tag)),
        }
    }
}

impl EncodeSize for OrderStatus {
    fn encode_size(&self) -> usize {
        1
    }
}

/// Market metadata owned by the CLOB.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Market {
    pub id: MarketId,
    pub base_asset: AssetId,
    pub quote_asset: AssetId,
    pub tick_size: u128,
    pub lot_size: u128,
    pub created_by: Address,
    pub created_at_height: u64,
    pub created_at_ms: u64,
}

impl Write for Market {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        self.id.write(buf);
        self.base_asset.write(buf);
        self.quote_asset.write(buf);
        self.tick_size.write(buf);
        self.lot_size.write(buf);
        self.created_by.write(buf);
        self.created_at_height.write(buf);
        self.created_at_ms.write(buf);
    }
}

impl Read for Market {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        Ok(Self {
            id: MarketId::read(buf)?,
            base_asset: AssetId::read(buf)?,
            quote_asset: AssetId::read(buf)?,
            tick_size: u128::read(buf)?,
            lot_size: u128::read(buf)?,
            created_by: Address::read(buf)?,
            created_at_height: u64::read(buf)?,
            created_at_ms: u64::read(buf)?,
        })
    }
}

impl EncodeSize for Market {
    fn encode_size(&self) -> usize {
        self.id.encode_size()
            + self.base_asset.encode_size()
            + self.quote_asset.encode_size()
            + self.tick_size.encode_size()
            + self.lot_size.encode_size()
            + self.created_by.encode_size()
            + self.created_at_height.encode_size()
            + self.created_at_ms.encode_size()
    }
}

/// An order accepted by the CLOB.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Order {
    pub id: OrderId,
    pub owner: Address,
    pub market: MarketId,
    pub side: Side,
    pub price: u128,
    pub original_base: u128,
    pub remaining_base: u128,
    pub filled_base: u128,
    pub status: OrderStatus,
    pub sequence: u64,
    pub created_at_height: u64,
    pub created_at_ms: u64,
}

impl Write for Order {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        self.id.write(buf);
        self.owner.write(buf);
        self.market.write(buf);
        self.side.write(buf);
        self.price.write(buf);
        self.original_base.write(buf);
        self.remaining_base.write(buf);
        self.filled_base.write(buf);
        self.status.write(buf);
        self.sequence.write(buf);
        self.created_at_height.write(buf);
        self.created_at_ms.write(buf);
    }
}

impl Read for Order {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        Ok(Self {
            id: OrderId::read(buf)?,
            owner: Address::read(buf)?,
            market: MarketId::read(buf)?,
            side: Side::read(buf)?,
            price: u128::read(buf)?,
            original_base: u128::read(buf)?,
            remaining_base: u128::read(buf)?,
            filled_base: u128::read(buf)?,
            status: OrderStatus::read(buf)?,
            sequence: u64::read(buf)?,
            created_at_height: u64::read(buf)?,
            created_at_ms: u64::read(buf)?,
        })
    }
}

impl EncodeSize for Order {
    fn encode_size(&self) -> usize {
        self.id.encode_size()
            + self.owner.encode_size()
            + self.market.encode_size()
            + self.side.encode_size()
            + self.price.encode_size()
            + self.original_base.encode_size()
            + self.remaining_base.encode_size()
            + self.filled_base.encode_size()
            + self.status.encode_size()
            + self.sequence.encode_size()
            + self.created_at_height.encode_size()
            + self.created_at_ms.encode_size()
    }
}

/// A deterministic execution record generated by matching one taker against one maker.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Fill {
    pub id: FillId,
    pub market: MarketId,
    pub maker_order: OrderId,
    pub taker_order: OrderId,
    pub maker: Address,
    pub taker: Address,
    pub taker_side: Side,
    pub price: u128,
    pub base_quantity: u128,
    pub quote_quantity: u128,
    pub sequence: u64,
    pub written_at_height: u64,
    pub written_at_ms: u64,
}

impl Write for Fill {
    fn write(&self, buf: &mut impl bytes::BufMut) {
        self.id.write(buf);
        self.market.write(buf);
        self.maker_order.write(buf);
        self.taker_order.write(buf);
        self.maker.write(buf);
        self.taker.write(buf);
        self.taker_side.write(buf);
        self.price.write(buf);
        self.base_quantity.write(buf);
        self.quote_quantity.write(buf);
        self.sequence.write(buf);
        self.written_at_height.write(buf);
        self.written_at_ms.write(buf);
    }
}

impl Read for Fill {
    type Cfg = ();

    fn read_cfg(buf: &mut impl bytes::Buf, _: &Self::Cfg) -> Result<Self, Error> {
        Ok(Self {
            id: FillId::read(buf)?,
            market: MarketId::read(buf)?,
            maker_order: OrderId::read(buf)?,
            taker_order: OrderId::read(buf)?,
            maker: Address::read(buf)?,
            taker: Address::read(buf)?,
            taker_side: Side::read(buf)?,
            price: u128::read(buf)?,
            base_quantity: u128::read(buf)?,
            quote_quantity: u128::read(buf)?,
            sequence: u64::read(buf)?,
            written_at_height: u64::read(buf)?,
            written_at_ms: u64::read(buf)?,
        })
    }
}

impl EncodeSize for Fill {
    fn encode_size(&self) -> usize {
        self.id.encode_size()
            + self.market.encode_size()
            + self.maker_order.encode_size()
            + self.taker_order.encode_size()
            + self.maker.encode_size()
            + self.taker.encode_size()
            + self.taker_side.encode_size()
            + self.price.encode_size()
            + self.base_quantity.encode_size()
            + self.quote_quantity.encode_size()
            + self.sequence.encode_size()
            + self.written_at_height.encode_size()
            + self.written_at_ms.encode_size()
    }
}
