name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Check Formatting
        run: cargo fmt --all -- --check

  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install mold
        run: command -v mold || (sudo apt-get update && sudo apt-get install -y mold)

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          components: llvm-tools-preview

      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Expose Runtime
        uses: crazy-max/ghaction-github-runtime@v4

      - name: Run Tests and Collect Coverage
        run: |
          cargo llvm-cov --locked --no-report nextest --workspace
          cargo llvm-cov report --locked --codecov --output-path codecov.info

      - name: Upload Coverage Data
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: codecov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rust

  unused-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install mold
        run: command -v mold || (sudo apt-get update && sudo apt-get install -y mold)

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install udeps
        uses: taiki-e/install-action@cargo-udeps

      - name: Check Unused Dependencies
        run: cargo udeps --locked --all-features --all-targets

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          (command -v mold && pkg-config --exists fontconfig) || \
            (sudo apt-get update && sudo apt-get install -y fontconfig libfontconfig1-dev mold)

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          components: clippy

      - name: Run Clippy
        run: cargo clippy --locked --all --all-targets -- -D warnings
